# .github/actions/docker-compose/action.yml
name: 'Docker-Compose Setup'
description: 'Sets up docker-compose'
runs:
  using: 'composite'
  steps:
    - uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.14.2' # the full version of `docker-compose` command